'use client'

import { useMemo, useState } from 'react'
import { ArrowUpRight, Check, Menu, Plus, ShoppingBag, X } from 'lucide-react'
import { products, money } from '../lib/types'
import { useCart } from '../lib/store'

export default function Home() {
  const { cart, add, remove } = useCart()
  const [showCart, setShowCart] = useState(false)
  const [notice, setNotice] = useState('')
  const subtotal = useMemo(() => cart.reduce((sum, item) => sum + item.price, 0), [cart])
  function addToCart(product: typeof products[number]) { add(product); setNotice(`${product.name} added to your cart`); setTimeout(() => setNotice(''), 2400) }
  return <main>
    <header className="shell nav">
      <a className="logo" href="#top"><span className="logo-mark" />PrintForge</a>
      <nav className="nav-links"><a href="/products">Shop</a><a href="#how">How it works</a><a href="/custom-print">Custom print</a></nav>
      <div className="nav-actions"><button className="icon-btn" aria-label="Open menu"><Menu size={19}/></button><a className="icon-btn" aria-label="Open cart" href="/cart"><ShoppingBag size={19}/>{cart.length > 0 && <span className="cart-count">{cart.length}</span>}</a></div>
    </header>
    <section className="shell hero" id="top"><div><div className="eyebrow">3D printed objects / Colombo</div><h1>Custom ideas.<br/><span style={{color:'var(--orange)'}}>Physical</span> creations.</h1><p className="hero-copy">Shop ready-to-print creations or turn your own 3D designs into something you can hold, use, and keep.</p><div className="actions"><a className="btn" href="/products">Shop products <ArrowUpRight size={15} style={{verticalAlign:'middle'}}/></a><a className="btn secondary" href="/custom-print">Start a custom print</a></div></div><div className="hero-art"><div className="sculpture"><div className="sculpture-tip"/></div><span className="stamp">EST. 2024 / PF-001</span></div></section>
    <div className="ticker"><span>●</span> Made to order in Sri Lanka <span>●</span> Small batch objects <span>●</span> Your idea, made physical <span>●</span> Made to order in Sri Lanka</div>
    <section className="shell section" id="shop"><div className="section-head"><div><div className="eyebrow">The collection / 04 pieces</div><h2>Useful things, made better.</h2></div><a className="section-note" href="#shop">View all products <ArrowUpRight size={14} style={{verticalAlign:'middle'}}/></a></div><div className="product-grid">{products.map(product => <article className="product-card" key={product.id}><div className="product-image" style={{background:product.tone}}><img src={product.image} alt={product.name}/></div><div className="product-meta"><div className="product-category">{product.category}</div><div className="product-name">{product.name}</div><div className="product-bottom"><span className="price">{money(product.price)}</span><button className="add" aria-label={`Add ${product.name}`} onClick={() => add(product)}><Plus size={17}/></button></div></div></article>)}</div></section>
    <section className="shell section"><div className="section-head"><div><div className="eyebrow">Browse by intention</div><h2>Find your next object.</h2></div></div><div className="categories"><div className="category">Desk setup <small>06 OBJECTS <ArrowUpRight size={16}/></small></div><div className="category">Phone & tech <small>04 OBJECTS <ArrowUpRight size={16}/></small></div><div className="category">Play & collect <small>08 OBJECTS <ArrowUpRight size={16}/></small></div><div className="category">Home rituals <small>05 OBJECTS <ArrowUpRight size={16}/></small></div></div></section>
    <section className="shell section" id="how"><div className="section-head"><div><div className="eyebrow">From pixels to presence</div><h2>Simple by design.</h2></div></div><div className="steps"><div className="step"><div className="step-number">01 / DISCOVER</div><h3>Choose your object</h3><p>Thoughtful, everyday forms designed in our small studio and printed in considered batches.</p></div><div className="step"><div className="step-number">02 / SPECIFY</div><h3>Make it yours</h3><p>Pick a material, select a finish, or send us your own 3D model to bring to life.</p></div><div className="step"><div className="step-number">03 / RECEIVE</div><h3>Hold the result</h3><p>We print, check, and dispatch your piece from Colombo. No mystery, just good making.</p></div></div></section>
    <section className="shell section" id="custom"><div className="cta"><div><div className="eyebrow" style={{color:'var(--ink)'}}>Custom printing / STL + 3MF</div><h2>Have the file?<br/>We have the material.</h2></div><a className="btn" href="/custom-print">Start your request <ArrowUpRight size={15} style={{verticalAlign:'middle'}}/></a></div></section>
    <footer className="shell footer"><span>© 2024 PrintForge</span><span>Custom ideas. Physical creations.</span></footer>
    {notice && <div style={{position:'fixed',bottom:24,left:'50%',transform:'translateX(-50%)',background:'var(--ink)',color:'white',padding:'14px 18px',fontSize:13,zIndex:5,display:'flex',gap:10,alignItems:'center'}}><Check size={16} color="var(--lime)"/>{notice}</div>}
    {showCart && <div style={{position:'fixed',inset:0,background:'rgba(23,23,23,.32)',zIndex:10}} onClick={() => setShowCart(false)}><aside style={{position:'absolute',right:0,top:0,bottom:0,width:'min(410px, 100%)',background:'var(--paper)',padding:28}} onClick={event => event.stopPropagation()}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2 style={{fontSize:27}}>Your cart <span style={{font:'12px DM Mono',color:'var(--muted)'}}>({cart.length})</span></h2><button className="icon-btn" onClick={() => setShowCart(false)} aria-label="Close cart"><X size={20}/></button></div>{cart.length === 0 ? <p className="hero-copy">Your cart is waiting for a good idea.</p> : <>{cart.map((item,index) => <div key={`${item.id}-${index}`} style={{display:'flex',gap:12,padding:'16px 0',borderBottom:'1px solid var(--line)'}}><div style={{width:55,height:55,background:item.tone}}/><div style={{flex:1,fontSize:13,fontWeight:800}}>{item.name}<div style={{font:'12px DM Mono',marginTop:8}}>{money(item.price)}</div></div><button className="icon-btn" onClick={() => remove(index)} aria-label={`Remove ${item.name}`}><X size={15}/></button></div>)}<div style={{display:'flex',justifyContent:'space-between',marginTop:24,fontWeight:800}}>Subtotal <span>{money(subtotal)}</span></div><button className="btn orange" style={{width:'100%',marginTop:22}}>Proceed to checkout</button></>}</aside></div>}
  </main>
}
